"""Create course_snapshots table

Revision ID: 7f3b94f3b8a8
Revises: 
Create Date: 2026-05-11 12:50:58.523794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3b94f3b8a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rating', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('difficulty', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('workload_hours_per_week', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('credit_hours', sa.Integer(), nullable=True),
    sa.Column('is_foundational', sa.Boolean(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=True),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_source_code_fetched', 'course_snapshots', ['source', 'course_code', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_source_code_fetched', table_name='course_snapshots')
    op.drop_table('course_snapshots')
    # ### end Alembic commands ###
